version: "23.0.5"
services: 
  dev-db: 
    image: postgres:13
    ports:
    # map the contianer port: 5432 to localhost port 5430
      - 5430:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dtth2802
      POSTGRES_DB: nest
    networks:
      - postgres-network
  test-db: 
    image: postgres:13
    ports:
    # map the contianer port: 5432 to localhost port 5430
      - 5433:5435
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dtth2802
      POSTGRES_DB: nest
    networks:
      - postgres-network
networks:
  postgres-network: